version: '3.8'

services:
  web-dev:
    build:
      context: .
      target: development
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules  
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3001 
    networks:
      - app-network
    restart: unless-stopped